name: Request an ARC Annotation Use-Case
description: ARC use-cases can be variably complex and range from a single annotation-table for a certain measurement to a full-fledged ARC.
title: "[ARC Use-Case]: "
labels: 
  - arc-use-case
body:
  - type: textarea
    id: description
    attributes:
      description: Please describe the use-case, add any relevant context. 
      label: Description
    validations:
      required: false
  - type: textarea
    id: resources
    attributes:
      label: Resources
      description: Share links to existing resources, standards, repositories, ARCs, 
    validations:
      required: false
